services:
  oceens:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ${LOCAL_DATABASE_DIR:-./database}:/app/database
      - ./src/oceens/import:/app/src/oceens/import
    restart: always
